INSERT INTO categorias (cat_estado,cat_nombre) values(1,"indumentaria")
INSERT INTO categorias (cat_estado,cat_nombre) values(1,"alimento")
INSERT INTO categorias (cat_estado,cat_nombre) values(1,"juguete")
INSERT INTO categorias (cat_estado,cat_nombre) values(1,"remedios")
INSERT INTO provincias (pro_estado,pro_nombre) values(1,"Buenos Aires")
INSERT INTO provincias (pro_estado,pro_nombre) values(1,"Catamarca")
INSERT INTO provincias (pro_estado,pro_nombre) values(1,"Chaco")
INSERT INTO provincias (pro_estado,pro_nombre) values(1,"Chubut")
